//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace it.invisiblefarm.dizionaricondivisi.DizionariCondivisiSpid.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("it.invisiblefarm.dizionaricondivisi.DizionariCondivisiSpid.App_LocalResources.Set" +
                            "tings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DizionariCondivisiSpid Item Basic Settings.
        /// </summary>
        public static string BasicSettings_Text {
            get {
                return ResourceManager.GetString("BasicSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DizionariCondivisiSpid Settings.
        /// </summary>
        public static string ControlTitle_settings_Text {
            get {
                return ResourceManager.GetString("ControlTitle_settings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servizio.
        /// </summary>
        public static string lblServizio {
            get {
                return ResourceManager.GetString("lblServizio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback DB gateway SPID.
        /// </summary>
        public static string lblServizio_Help {
            get {
                return ResourceManager.GetString("lblServizio.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string lblUrl {
            get {
                return ResourceManager.GetString("lblUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL del gateway SPID.
        /// </summary>
        public static string lblUrl_Help {
            get {
                return ResourceManager.GetString("lblUrl.Help", resourceCulture);
            }
        }
    }
}
